# Generated by Django 3.1.7 on 2021-03-29 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210329_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetable',
            name='userid',
            field=models.CharField(default=datetime.datetime(2021, 3, 29, 16, 1, 52, 37745, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
